export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const RECIPES_LIST_ROUTE = '/'
export const SAVED_ROUTE = '/saved'
export const RECIPES_ROUTE = 'RECIPES'